# Metadata Proyek
sonar.projectKey=stockvision-monorepo
sonar.projectName=StockVision
sonar.projectVersion=1.0.0

# Jalur Sumber Code (Menganalisis frontend dan backend secara bersamaan)
sonar.sources=backend,frontend/src

# File yang Dikecualikan dari Analisis
sonar.exclusions=**/node_modules/**,**/venv/**,**/tests/**,**/*.spec.js,backend/db/database.sql,frontend/dist/**

# Konfigurasi Encoding
sonar.sourceEncoding=UTF-8

# Konfigurasi Spesifik Bahasa
sonar.python.version=3.10
sonar.javascript.environments=browser
