# Metadata Proyek SonarCloud
sonar.organization=internsigma
sonar.projectKey=internSIGMA_stockVision
sonar.projectName=StockVision
sonar.projectVersion=1.0.0

# Alamat Server SonarCloud
sonar.host.url=https://sonarcloud.io

# Jalur Sumber Code
sonar.sources=backend,frontend/src

# File yang Dikecualikan dari Analisis
sonar.exclusions=**/node_modules/**,**/venv/**,**/tests/**,**/*.spec.js,backend/db/database.sql,frontend/dist/**

# Konfigurasi Encoding & Bahasa
sonar.sourceEncoding=UTF-8
sonar.python.version=3.10
sonar.javascript.environments=browser
